# Generated by Django 3.1.3 on 2020-11-20 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consultant',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
